// lang.js — all language/config data for Suno Tag Generator
// Edit this file to add translations or new wizard steps.
"use strict";

const WIZARD_STEPS_DEF = [
  { id:'genre',       icon:'🎵', color:'#8b5cf6' },
  { id:'mood',        icon:'✨', color:'#3b82f6' },
  { id:'instruments', icon:'🎹', color:'#14b8a6' },
  { id:'tags',        icon:'🏷️',  color:'#22c55e' },
  { id:'vocals',      icon:'🎤', color:'#ec4899' },
  { id:'production',  icon:'🎚️',  color:'#f97316' },
  { id:'validate',    icon:'✅', color:'#22c55e' },
];

const LANG = {
  en: {
    intro: {
      title: "Welcome to Rick AI",
      tagline: "Your assistant for creating music with AI",
      body: "Suno AI generates complete music from a text description. The more precise your description, the closer the result will be to what you imagine. Rick AI guides you through 6 steps to build that perfect description.",
      whatYouGet: "At the end, you get:",
      styleLabel: "Style Field",
      styleDesc: "The musical description to paste into Suno",
      lyricsLabel: "Lyrics Box",
      lyricsDesc: "The lyrics with structure and vocal commands",
      excludeLabel: "Exclude Field",
      excludeDesc: "Elements to avoid in the music",
      start: "Get Started →",
      skip: "Skip",
      reopen: "Guide",
      steps: [
        { icon: "🎵", label: "Genre",        desc: "What music style?", ex: "e.g. Kompa, Zouk, R&B" },
        { icon: "✨", label: "Mood",          desc: "What is the feel?", ex: "e.g. Melancholic, Festive, Epic" },
        { icon: "🎹", label: "Instruments",   desc: "Which instruments?", ex: "e.g. Piano, Guitar, Brass" },
        { icon: "🏷️", label: "Details",       desc: "Technical finishing touches", ex: "e.g. Slow tempo, Minor key" },
        { icon: "🎤", label: "Vocals",        desc: "How does the singer sound?", ex: "e.g. Soprano, Raspy, Vibrato" },
        { icon: "🎚️", label: "Production",    desc: "The final sonic colour", ex: "e.g. Lo-fi, Deep reverb, Cinematic" },
      ],
    },
    next: "Next →", back: "← Back", finish: "Done ✓",
    stepOf: "of", genreRequired: "Select a genre to continue",
    changeGenre: "↩ Change",
    addCustom: "+ Custom",
    customSubgenrePh: "Custom sub-genre…",
    customMoodPh: "Custom mood…",
    artistPh: "e.g. in the style of Frank Ocean",
    customStylePh: "Add anything here — it goes verbatim into the style field…",
    vocalistNamePh: "Vocalist name (optional)…",
    noVocalists: "No saved vocalists yet",
    guidedTab: "Guided", freeformTab: "Free Form",
    songStructLabel: "Song Structure",
    lyricsWarning: "Lyrics box: lyrics + structural tags ONLY",
    presetsBtn: "⭐ Presets", importBtn: "⬆ Import", exportBtn: "⬇ Export",
    copyBtn: "Copy", useBtn: "Use", saveBtn: "Save", clearBtn: "Clear",
    genreAnchorTitle: "Genre Anchor",
    genreAnchorHint: "Most important — v5 builds the entire production framework from this",
    subtitle: "Suno v5 precision prompt builder",
    noGenreHint: "Select a genre to start building your v5 prompt",
    restartBtn: "Start Over",
    saveAsTitle: "Save Vocalist As",
    saveAsPlaceholder: "Vocalist name...",
    saveAsOk: "Save",
    saveAsCancel: "Cancel",
    artistRefHowToLabel: "How to use:",
    artistRefHowToBody: "Artist references encode instrumentation, tone, era, and emotional register in a single phrase. Use <em>Artist-style</em> for broad influence, <em>Artist + era</em> for a specific sound, or <em>Artist + technique</em> for a specific element.",
    artistRefNone: "No curated references for this genre — type any artist name above.",
    artistRefPh: "e.g. Miles Davis Kind of Blue-era, J Dilla-style drums...",
    cmdBlockLabel: "Lyrics command block:",
    cmdBlockHint: "Paste at the very top of your lyrics, before any section tags",
    lyricsCopyBtn: "Copy lyrics", deliveryPick: "pick any",
    timbreLabel: "Timbre keywords", pitchLabel: "Pitch register",
    cmdBlockLabel: "Command block",
    cmdBlockHint: "Paste at the very top of your lyrics, before [Verse 1]",
    genreAnchorTitle: "Genre Anchor",
    genreAnchorHint: "Most important — v5 builds everything from this",
    steps: {
      genre: "Genre", mood: "Mood & Tempo", instruments: "Instruments",
      tags: "Tags & Extras", vocals: "Vocals & Lyrics", production: "Production"
    },
    validate: {
      title: "Validate Prompt",
      hint: "Review your settings before generating.",
      score: "Prompt Score",
      perfect: "Perfect",
      good: "Good",
      fair: "Fair",
      weak: "Needs Work",
      noIssues: "No issues found — your prompt looks great!",
      errors: "Errors",
      warnings: "Warnings",
      tips: "Tips",
      excludeSection: "Excludes",
      excludeEmpty: "Nothing excluded",
      generateBtn: "Copy & Generate",
    },
    section: {
      subgenre:  { title: "Sub-Genre", hint: "Refine the genre anchor for a more specific sound" },
      mood:      { title: "Mood", hint: "Set the emotional energy — stack 2–3 moods for best results" },
      tempo:     { title: "Tempo", hint: "Beats per minute — leave at the genre default if unsure" },
      instruments:{ title: "Instruments", hint: "Core instruments — order matters, first = most dominant" },
      production:{ title: "Production Style", hint: "How the mix should feel — warm, raw, polished, spacious…" },
      quality:   { title: "Quality & Tags", hint: "Push render fidelity with quality flags" },
      vocal:     { title: "Vocal Meta-Tags", hint: "Control gender, presence, and style of the vocal" },
      metaprod:  { title: "Meta: Production", hint: "Advanced production meta-tags for sound design" },
      metamood:  { title: "Meta: Mood", hint: "Emotional meta-tags beyond the standard mood chips" },
      artistref: { title: "Artist Reference", hint: "Anchor the style to a real artist — use sparingly" },
      exclude:   { title: "Exclude Styles", hint: "Anything listed here the AI will try to avoid" },
      moreopts:  { title: "More Options", hint: "Gender toggle, weirdness, style influence" },
      custom:    { title: "Custom Style Text", hint: "Written verbatim into the style field" },
      lyrics:    { title: "Lyric Structure", hint: "Build lyrics with structural tags and delivery markers" },
      vocbuild:  { title: "Vocalist Profile", hint: "Set vocal register, timbre, and persona" }
    }
  },
  fr: {
    intro: {
      title: "Bienvenue dans Rick AI",
      tagline: "Votre assistant pour créer de la musique avec l'IA",
      body: "Suno AI génère de la musique complète à partir d'une description textuelle. Plus votre description est précise, plus le résultat sera proche de ce que vous imaginez. Rick AI vous guide en 6 étapes pour construire cette description parfaite.",
      whatYouGet: "À la fin, vous obtenez :",
      styleLabel: "Champ Style",
      styleDesc: "La description musicale à coller dans Suno",
      lyricsLabel: "Boîte de Paroles",
      lyricsDesc: "Les paroles avec structure et commandes vocales",
      excludeLabel: "Champ Exclusions",
      excludeDesc: "Les éléments à éviter dans la musique",
      start: "Commencer →",
      skip: "Passer",
      reopen: "Guide",
      steps: [
        { icon: "🎵", label: "Genre",       desc: "Quel style de musique ?", ex: "ex. Kompa, Zouk, R&B" },
        { icon: "✨", label: "Ambiance",     desc: "Comment ça doit sonner ?", ex: "ex. Mélancolique, Festif, Épique" },
        { icon: "🎹", label: "Instruments",  desc: "Quels instruments ?", ex: "ex. Piano, Guitare, Cuivres" },
        { icon: "🏷️", label: "Détails",      desc: "Les finitions techniques", ex: "ex. Tempo lent, Mode mineur" },
        { icon: "🎤", label: "Voix",         desc: "Comment chante le chanteur ?", ex: "ex. Soprano, Rauque, Vibrato" },
        { icon: "🎚️", label: "Production",   desc: "La couleur sonore finale", ex: "ex. Lo-fi, Reverb, Cinématique" },
      ],
    },
    next: "Suivant →", back: "← Retour", finish: "Terminé ✓",
    stepOf: "sur", genreRequired: "Sélectionnez un genre pour continuer",
    changeGenre: "↩ Changer",
    addCustom: "+ Personnalisé",
    customSubgenrePh: "Sous-genre personnalisé…",
    customMoodPh: "Ambiance personnalisée…",
    artistPh: "ex : dans le style de Frank Ocean",
    customStylePh: "Ajoutez n'importe quoi ici — inséré tel quel dans le champ de style…",
    vocalistNamePh: "Nom du chanteur (optionnel)…",
    noVocalists: "Aucun chanteur sauvegardé",
    guidedTab: "Guidé", freeformTab: "Forme libre",
    songStructLabel: "Structure de la chanson",
    lyricsWarning: "Zone de paroles : paroles + tags structurels UNIQUEMENT",
    presetsBtn: "⭐ Préréglages", importBtn: "⬆ Importer", exportBtn: "⬇ Exporter",
    copyBtn: "Copier", useBtn: "Utiliser", saveBtn: "Sauvegarder", clearBtn: "Effacer",
    genreAnchorTitle: "Ancre de Genre",
    genreAnchorHint: "Le plus important — v5 construit tout le cadre de production à partir de ça",
    subtitle: "Générateur de prompts précis pour Suno v5",
    noGenreHint: "Sélectionnez un genre pour commencer à construire votre prompt v5",
    restartBtn: "Recommencer",
    saveAsTitle: "Sauvegarder le chanteur sous",
    saveAsPlaceholder: "Nom du chanteur...",
    saveAsOk: "Sauvegarder",
    saveAsCancel: "Annuler",
    artistRefHowToLabel: "Comment utiliser :",
    artistRefHowToBody: "Les références d'artiste encodent l'instrumentation, le ton, l'ère et le registre émotionnel en une seule phrase. Utilisez <em>style-Artiste</em> pour une influence large, <em>Artiste + ère</em> pour un son précis, ou <em>Artiste + technique</em> pour un élément spécifique.",
    artistRefNone: "Aucune référence pour ce genre — tapez directement un nom d'artiste ci-dessus.",
    artistRefPh: "ex : Miles Davis Kind of Blue-era, J Dilla-style drums...",
    cmdBlockLabel: "Bloc de commande vocal :",
    cmdBlockHint: "Collez tout en haut de vos paroles, avant les tags de section",
    lyricsCopyBtn: "Copier les paroles", deliveryPick: "choisir",
    timbreLabel: "Mots-clés timbre", pitchLabel: "Registre de hauteur",
    cmdBlockLabel: "Bloc de commande",
    cmdBlockHint: "Collez tout en haut de vos paroles, avant [Verse 1]",
    genreAnchorTitle: "Genre Ancre",
    genreAnchorHint: "Le plus important — v5 construit tout à partir de ça",
    steps: {
      genre: "Genre", mood: "Ambiance & Tempo", instruments: "Instruments",
      tags: "Tags & Extras", vocals: "Voix & Paroles", production: "Production"
    },
    validate: {
      title: "Valider le Prompt",
      hint: "Vérifiez vos réglages avant de générer.",
      score: "Score du Prompt",
      perfect: "Parfait",
      good: "Bon",
      fair: "Passable",
      weak: "À améliorer",
      noIssues: "Aucun problème — votre prompt est excellent !",
      errors: "Erreurs",
      warnings: "Avertissements",
      tips: "Conseils",
      excludeSection: "Exclusions",
      excludeEmpty: "Rien d'exclu",
      generateBtn: "Copier & Générer",
    },
    section: {

      subgenre:  { title: "Sous-Genre", hint: "Affinez l'ancrage pour un son plus précis" },
      mood:      { title: "Ambiance", hint: "Définissez l'énergie émotionnelle — 2–3 ambiances pour de meilleurs résultats" },
      tempo:     { title: "Tempo", hint: "Battements par minute — laissez le défaut du genre si vous n'êtes pas sûr" },
      instruments:{ title: "Instruments", hint: "Instruments principaux — l'ordre compte, le premier domine" },
      production:{ title: "Style de Production", hint: "Comment le mix doit sonner — chaud, brut, poli, spacieux…" },
      quality:   { title: "Qualité & Tags", hint: "Améliorez la fidélité du rendu avec des indicateurs de qualité" },
      vocal:     { title: "Méta-Tags Vocaux", hint: "Contrôlez le genre, la présence et le style vocal" },
      metaprod:  { title: "Méta: Production", hint: "Méta-tags de production avancés pour le design sonore" },
      metamood:  { title: "Méta: Ambiance", hint: "Méta-tags émotionnels au-delà des chips standard" },
      artistref: { title: "Référence Artiste", hint: "Ancrez le style sur un vrai artiste — à utiliser avec parcimonie" },
      exclude:   { title: "Styles à Exclure", hint: "Tout ce qui est listé ici sera évité par l'IA" },
      moreopts:  { title: "Plus d'Options", hint: "Bouton de genre, étrangeté, influence de style" },
      custom:    { title: "Style Personnalisé", hint: "Inséré tel quel dans le champ de style" },
      lyrics:    { title: "Structure des Paroles", hint: "Construisez vos paroles avec des tags structurels et des marqueurs de livraison" },
      vocbuild:  { title: "Profil Vocal", hint: "Définissez le registre, le timbre et la persona vocale" }
    }
  }
};

// ─── KB_TEXT — translatable descriptions for genres & tags ────────────────
// Key = genre.id  or  exact tag string like "[No Vocals]"
const KB_TEXT = {
  en: {
    genres: {
      "melodic-dubstep": "Emotional electronic with melodic elements and heavy dubstep drops",
      "future-bass":     "Colorful high-energy electronic with pitched vocals and heavy drops",
      "house":           "Four-on-the-floor groove-driven electronic dance music",
      "lofi":            "Relaxed hazy hip hop with vintage sampling aesthetics",
      "dnb":             "High-speed breakbeat electronic with deep rolling basslines",
      "techno":          "Machine-driven hypnotic electronic with industrial aesthetics",
      "ambient":         "Atmospheric textural soundscapes without traditional song structure",
      "hip-hop":         "Rhythmic vocal-driven music with boom bap or modern production",
      "trap":            "Modern hip hop with heavy 808s, hi-hat rolls and atmospheric production",
      "boom-bap":        "Classic hip hop with jazz-inflected samples and hard-hitting drums",
      "rnb":             "Soul-influenced pop with smooth production and emotional vocals",
      "neo-soul":        "Modern soul with jazz influences and organic live instrumentation",
      "pop":             "Mainstream accessible music with catchy melodies and polished production",
      "indie-rock":      "Guitar-driven rock with artistic independence and emotional depth",
      "metal":           "Heavy aggressive guitar-driven music with complex arrangements",
      "jazz":            "Improvisational music with sophisticated harmony and swing feel",
      "orchestral":      "Full orchestra arrangements with classical or modern cinematic style",
      "cinematic":       "Film score-inspired music designed for emotional storytelling",
      "country":         "American roots music with storytelling lyrics and country instrumentation",
      "reggaeton":       "Latin urban music with dembow rhythm and dancehall influences",
      "afrobeats":       "West African-influenced pop with polyrhythmic percussion and infectious grooves",
      "kompa":           "Haitian dance music created in 1955 — infectious meringue-based rhythm, lush brass, and smooth electric guitar",
      "raboday":         "Modern Haitian urban genre — Kompa rhythms fused with trap, 808s, and raw street energy",
      "zouk":            "Caribbean dance music from the French Antilles — romantic vocals, flowing rhythms, and lush tropical production"
    },
    tags: {
      "[Hyper-Realistic]": "Highest-fidelity render. Captures breath, bow noise, room tone. Uses more credits — skip on test runs.",
      "[Studio Quality]":  "Broad quality baseline for all production styles. Pairs well with Hyper-Realistic.",
      "[Mastered]":        "Broadcast-ready: consistent loudness, final limiting, tonal balance.",
      "[No Vocals]":       "Removes all vocal content. Most reliable for instrumentals. Pair with 'no: vocals' for max effect.",
      "[Instrumental]":    "Alternative to No Vocals. Sometimes produces a warmer tone. Use if No Vocals still leaks vocals.",
      "[Female Vocal]":    "Feminine register and delivery. Best for R&B, pop, jazz, neo-soul.",
      "[Male Vocal]":      "Masculine register. Best for hip hop, soul, rock, jazz.",
      "[Powerful]":        "Projects full-voice intensity. Best for anthems, gospel, soul belting.",
      "[Whispered]":       "Intimate breathy delivery. Best for ASMR, ambient, confessional R&B.",
      "[Falsetto]":        "High register above the break. Best for neo-soul, R&B, indie pop.",
      "[Raspy]":           "Gritty, textured vocal tone. Best for blues, rock, dark hip hop.",
      "[Breathy]":         "Airy, soft texture. Best for lo-fi, dream pop, sensual R&B.",
      "[Sidechain]":       "Pumping compression — the kick ducks the other elements. Best for house, techno, EDM.",
      "[Lo-Fi]":           "Applies vinyl crackle, tape saturation, frequency roll-off. Best for lo-fi hip hop, indie, vintage warmth.",
      "[Dry Mix]":         "Removes excess reverb — close, intimate sound. Best for jazz, blues, intimate R&B.",
      "[Heavy Bass]":      "Increases sub-bass presence significantly. Best for hip hop, trap, bass music.",
      "[808]":             "Activates 808 bass drum and sub-bass engine. Best for trap, hip hop.",
      "[Distortion]":      "Adds harmonic distortion. Best for rock, blues, industrial, guitar-forward production.",
      "[Reverb]":          "Adds spacious room/hall reverb. Best for ambient, cinematic, any production needing space.",
      "[Cinematic]":       "Wide, dramatic production with large dynamic range. Best for film scores, trailers.",
      "[Orchestral]":      "Adds strings, brass, and orchestral arrangement. Best for classical, cinematic, orchestral hip hop.",
      "[Vintage]":         "Period-accurate production characteristics. Best for old school hip hop, classic R&B.",
      "[Live Drums]":      "Shifts drum programming toward organic, live-sounding patterns. Best for jazz, soul, rock.",
      "[Minimalist]":      "Strips back arrangement — fewer elements, more space. Best for ambient, intimate R&B, minimal techno.",
      "[Dark]":            "Shifts harmonic palette toward minor, dissonant, tense. Best for dark trap, noir jazz.",
      "[Euphoric]":        "High-energy, uplifting — major key, bright synths. Best for festival EDM, uplifting trance.",
      "[Melancholic]":     "Bittersweet, introspective — works with minor keys. Best for R&B ballads, indie, slow blues.",
      "[Aggressive]":      "High BPM feel, distorted elements, intense performance. Best for drill, heavy metal, dark trap.",
      "[Chill]":           "Low tempo, relaxed arrangement, warm tones. Best for lo-fi, chillout, ambient, late night R&B.",
      "[Dreamy]":          "Hazy, reverb-heavy, slow attack on instruments. Best for cloud rap, ambient, PBR&B.",
      "[Epic]":            "Large-scale, climactic builds. Best for cinematic scores, big room EDM, orchestral hip hop.",
      "[Tense]":           "Unresolved harmonic movement, building anxiety. Best for horror, thriller scores, dark ambient."
    }
  },
  fr: {
    genres: {
      "melodic-dubstep": "Électronique émotionnel avec éléments mélodiques et drops dubstep intenses",
      "future-bass":     "Électronique coloré et énergique avec voix pitchées et drops lourds",
      "house":           "Musique de danse électronique à groove soutenu sur quatre temps",
      "lofi":            "Hip-hop relaxé et brumeux avec esthétique de sampling vintage",
      "dnb":             "Électronique haute vitesse avec breakbeats et basses profondes et roulantes",
      "techno":          "Électronique hypnotique pilotée par machines avec esthétique industrielle",
      "ambient":         "Paysages sonores atmosphériques et texturaux sans structure de chanson traditionnelle",
      "hip-hop":         "Musique vocale rythmique avec production boom bap ou moderne",
      "trap":            "Hip-hop moderne avec 808s lourds, roulements de hi-hat et production atmosphérique",
      "boom-bap":        "Hip-hop classique avec samples jazz et percussions percutantes",
      "rnb":             "Pop d'influence soul avec production lisse et voix émotionnelles",
      "neo-soul":        "Soul moderne avec influences jazz et instrumentation live organique",
      "pop":             "Musique grand public avec mélodies accrocheuses et production soignée",
      "indie-rock":      "Rock guitare avec indépendance artistique et profondeur émotionnelle",
      "metal":           "Musique de guitare lourde et agressive avec arrangements complexes",
      "jazz":            "Musique d'improvisation avec harmonie sophistiquée et feel de swing",
      "orchestral":      "Arrangements d'orchestre complet en style classique ou cinématographique",
      "cinematic":       "Musique inspirée de bandes originales conçue pour la narration émotionnelle",
      "country":         "Musique roots américaine avec paroles narratives et instrumentation country",
      "reggaeton":       "Musique urbaine latine avec rythme dembow et influences dancehall",
      "afrobeats":       "Pop d'influence ouest-africaine avec percussions polyrythmiques et grooves entraînants",
      "kompa":           "Musique de danse haïtienne créée en 1955 — rythme meringue, cuivres luxuriants et guitare électrique douce",
      "raboday":         "Genre urbain haïtien moderne — rythmes Kompa fusionnés avec trap, 808s et énergie brute de la rue",
      "zouk":            "Musique de danse caribéenne des Antilles françaises — voix romantiques, rythmes fluides et production tropicale"
    },
    tags: {
      "[Hyper-Realistic]": "Rendu haute fidélité. Capture la respiration, le bruit d'archet, la résonance. Utilise plus de crédits — évitez pour les tests.",
      "[Studio Quality]":  "Référence de qualité large pour tous les styles. Se marie bien avec Hyper-Realistic.",
      "[Mastered]":        "Prêt pour la diffusion : loudness cohérent, limitation finale, équilibre tonal.",
      "[No Vocals]":       "Supprime tout contenu vocal. Le plus fiable pour les instrumentaux. Associez avec 'no: vocals' pour un effet maximal.",
      "[Instrumental]":    "Alternative à No Vocals. Produit parfois un son plus chaud. À utiliser si No Vocals laisse passer des voix.",
      "[Female Vocal]":    "Registre et livraison féminins. Idéal pour R&B, pop, jazz, neo-soul.",
      "[Male Vocal]":      "Registre masculin. Idéal pour Kompa,hip-hop, soul, rock, jazz.",
      "[Powerful]":        "Projette une intensité pleine voix. Idéal pour les hymnes, le gospel et le soul.",
      "[Whispered]":       "Livraison intime et soufflée. Idéale pour l'ASMR, l'ambient et le R&B confessionnel.",
      "[Falsetto]":        "Registre aigu au-dessus du break. Idéal pour neo-soul, R&B, indie pop.",
      "[Raspy]":           "Timbre vocal granuleux et texturé. Idéal pour blues, rock, hip-hop sombre.",
      "[Breathy]":         "Texture aérienne et douce. Idéale pour lo-fi, dream pop, R&B sensuel.",
      "[Sidechain]":       "Compression à pompage — le kick fait baisser les autres éléments. Idéal pour house, techno, EDM.",
      "[Lo-Fi]":           "Applique craquements vinyle, saturation cassette et coupure de fréquences. Idéal pour hip-hop lo-fi, indie.",
      "[Dry Mix]":         "Supprime l'excès de réverbération — son proche et intime. Idéal pour jazz, blues, R&B intime.",
      "[Heavy Bass]":      "Augmente significativement la présence des basses sub. Idéal pour hip-hop, trap.",
      "[808]":             "Active le moteur de grosse caisse 808 et de basses sub. Idéal pour trap, hip-hop.",
      "[Distortion]":      "Ajoute de la distorsion harmonique. Idéal pour rock, blues, industriel.",
      "[Reverb]":          "Ajoute une réverbération spacieuse. Idéal pour ambient, cinématographique.",
      "[Cinematic]":       "Production large et dramatique avec grande plage dynamique. Idéal pour bandes originales.",
      "[Orchestral]":      "Ajoute cordes, cuivres et arrangement orchestral. Idéal pour classique, cinématographique.",
      "[Vintage]":         "Caractéristiques de production d'époque. Idéal pour old school hip-hop, R&B classique.",
      "[Live Drums]":      "Oriente la batterie vers des patterns organiques. Idéal pour jazz, soul, rock.",
      "[Minimalist]":      "Réduit l'arrangement — moins d'éléments, plus d'espace. Idéal pour ambient, R&B intime.",
      "[Dark]":            "Oriente la palette harmonique vers le mineur et la tension. Idéal pour dark trap, jazz noir.",
      "[Euphoric]":        "Haute énergie, élévant — tonalité majeure, synthés brillants. Idéal pour EDM festival, trance.",
      "[Melancholic]":     "Doux-amer, introspectif. Idéal pour ballades R&B, indie, blues lent.",
      "[Aggressive]":      "BPM élevé, éléments distordus, performance intense. Idéal pour drill, metal, dark trap.",
      "[Chill]":           "Tempo bas, arrangement détendu, tons chauds. Idéal pour lo-fi, chillout, R&B nocturne.",
      "[Dreamy]":          "Brumeux, réverbération intense, attaque lente. Idéal pour cloud rap, ambient, PBR&B.",
      "[Epic]":            "Grande échelle, constructions climatiques. Idéal pour bandes originales, EDM grande salle.",
      "[Tense]":           "Mouvement harmonique non résolu, anxiété croissante. Idéal pour horreur, thriller, dark ambient."
    }
  }
};

// CHIP_HINTS
const CHIP_HINTS = {
  en: {
    "Aggressive":"High intensity, confrontational energy",
    "Boastful":"Confident self-promotion and swagger",
    "Confident":"Assured, self-assured energy",
    "Contemplative":"Thoughtful, meditative atmosphere",
    "Cozy":"Warm, comfortable, intimate feeling",
    "Dark":"Somber, shadowy emotional undertone",
    "Defiant":"Rebellious resistance to authority",
    "Dramatic":"Heightened tension and emotion",
    "Dreamy":"Soft, floating, fantasy-like quality",
    "Driving":"Forward-moving rhythmic momentum",
    "Emotional":"Deep emotional resonance and feeling",
    "Energetic":"High physical and musical energy",
    "Epic":"Grand scale with cinematic sweep",
    "Ethereal":"Otherworldly, airy, delicate texture",
    "Euphoric":"Intense happiness, peak elation",
    "Festive":"Celebratory party atmosphere",
    "Groovy":"Funky, rhythmically compelling feel",
    "Hype":"Exciting build-up and adrenaline",
    "Inspiring":"Uplifting and motivating energy",
    "Intimate":"Close, personal, vulnerable feeling",
    "Introspective":"Self-reflective, inner-focused",
    "Joyful":"Pure happiness and lightness",
    "Melancholic":"Gentle sadness with beauty",
    "Minimal":"Sparse, restrained, spacious",
    "Nostalgic":"Evoking fond memories of the past",
    "Party":"High energy for dancing and celebration",
    "Peaceful":"Calm, harmonious tranquility",
    "Playful":"Light-hearted fun and whimsy",
    "Raw":"Unpolished, authentic, honest",
    "Rebellious":"Anti-establishment, punk attitude",
    "Romantic":"Love, longing, tender emotion",
    "Sensual":"Seductive, physically evocative",
    "Serene":"Peaceful, undisturbed calm",
    "Smooth":"Effortless flow without friction",
    "Sophisticated":"Refined, cultured, elegant",
    "Soulful":"Deep emotional authenticity",
    "Tense":"Anxious, suspenseful atmosphere",
    "Triumphant":"Victory, achievement, overcome",
    "Uplifting":"Raises the spirit, positive energy",
    "Anthemic":"Crowd-sweeping, sing-along quality",
    "Anxious":"Nervous, unsettled energy",
    "Assertive":"Direct, confident, pushing forward",
    "Atmospheric":"Immersive ambient texture",
    "Authentic":"Genuine, unaffected expression",
    "Bittersweet":"Joy and sadness intertwined",
    "Blue":"Classic blues-influenced sadness",
    "Bold":"Strong, fearless statement",
    "Bright":"Upbeat, luminous energy",
    "Brooding":"Deep, slow-burning darkness",
    "Brutal":"Unrelenting, crushing intensity",
    "Bubbly":"Light, effervescent cheerfulness",
    "Buoyant":"Lifted, resilient, floating",
    "Calm":"Quiet, low-tension state",
    "Calming":"Actively soothing the listener",
    "Carnival":"Playful, festive, fairground energy",
    "Celebratory":"Marking an achievement or joy",
    "Cheerful":"Bright, happy, positive",
    "Classic":"Timeless, well-established feel",
    "Cold":"Detached, icy emotional tone",
    "Confessional":"Personal, revealing, honest",
    "Cool":"Understated effortless style",
    "Crushing":"Overwhelming weight of emotion",
    "Danceable":"Irresistible rhythmic drive",
    "Dancefloor":"Optimized for club movement",
    "Deep":"Dense emotional or sonic depth",
    "Desolate":"Lonely, barren, empty feeling",
    "Devastating":"Overwhelming emotional impact",
    "Dominant":"Commanding, powerful presence",
    "Doom":"Slow, heavy, impending darkness",
    "Earnest":"Sincere, genuine, non-ironic",
    "Effortless":"Natural, flowing without strain",
    "Elegant":"Tasteful, refined beauty",
    "Fierce":"Powerful, intense, unrelenting",
    "Floating":"Weightless, suspended quality",
    "Frantic":"Fast-paced, chaotic energy",
    "Fresh":"New, crisp, contemporary feel",
    "Fun":"Lighthearted and enjoyable",
    "Funky":"Groove-heavy, syncopated rhythm",
    "Futuristic":"Forward-looking, sci-fi aesthetic",
    "Gritty":"Rough, earthy, unpolished texture",
    "Happy":"Straightforward positive emotion",
    "Haunting":"Lingers in memory, eerie beauty",
    "Heavy":"Dense, weighty sonic mass",
    "Hopeful":"Optimistic looking-forward feeling",
    "Hypnotic":"Repetitive, trance-inducing pattern",
    "Laid-back":"Relaxed, unhurried groove",
    "Lush":"Dense, rich, layered texture",
    "Majestic":"Grand, imposing, stately",
    "Mystical":"Spiritual, mysterious atmosphere",
    "Ominous":"Dark foreshadowing, threatening",
    "Optimistic":"Positive outlook and brightness",
    "Passionate":"Intense feeling and commitment",
    "Poetic":"Lyrical, imagery-rich expression",
    "Positive":"Affirmative, good-energy",
    "Punchy":"Strong attack, tight dynamics",
    "Reflective":"Looking inward or backward",
    "Sad":"Direct expression of sadness",
    "Sexy":"Suggestive, flirtatious energy",
    "Slow":"Reduced tempo, contemplative pace",
    "Spooky":"Unsettling, eerie atmosphere",
    "Summery":"Light, warm, seasonal brightness",
    "Upbeat":"Fast tempo with positive energy",
    "Urgent":"Pressing, time-sensitive feeling",
    "Vibrant":"Full of life and color",
    "Warm":"Comfortable, inviting quality",
    "[Whispered]":"Barely audible, intimate breath-tone delivery",
    "[Soft]":"Gentle, low-volume dynamics",
    "[Gentle]":"Tender, careful, non-aggressive delivery",
    "[Powerful]":"Full-voiced, high-energy projection",
    "[Belted]":"Chest-voice pushed at high volume",
    "[Shouted]":"Forceful, loud, declamatory delivery",
    "[Screamed]":"Extreme-volume, raw emotional release",
    "[Intense]":"High emotional charge and vocal focus",
    "[Smooth]":"Effortless, polished, gliding tone",
    "[Raspy]":"Gritty texture from vocal friction",
    "[Breathy]":"Air mixed into tone for intimacy",
    "[Airy]":"Light, floating, open resonance",
    "[Nasal]":"Forward resonance through the nasal cavity",
    "[Soulful]":"Deep emotion, R&B warmth",
    "[Operatic]":"Classical singing technique and power",
    "[Falsetto]":"Upper register above normal vocal range",
    "[Head Voice]":"Upper register with full resonance",
    "[Chest Voice]":"Strong lower register with full body",
    "[Melodic]":"Emphasis on tunefulness and melody",
    "[Tender]":"Vulnerable, caring, gentle tone",
    "[Aggressive]":"Hard, attacking vocal approach",
    "[Harmonies]":"Multiple vocal parts layered together",
    "[Ad-libs]":"Spontaneous embellishments between lines",
    "[Vocal Run]":"Rapid sequence of ascending or descending pitches",
    "[Melisma]":"Multiple notes sung on a single syllable",
    "[Vibrato]":"Oscillating pitch adds warmth and color",
    "[Staccato]":"Short, detached, separated notes",
    "[Legato]":"Smooth, connected flowing phrases",
    "[Choir]":"Multiple voices in group texture",
    "[Chant]":"Rhythmic repeated-phrase delivery",
    "[Growling]":"Guttural, aggressive vocal distortion",
    "[Rapped]":"Rhythmic spoken-word delivery",
    "[Fast Rap]":"High-speed rhyming flow",
    "[Slow Flow]":"Deliberate, measured rap pacing",
    "[Melodic Rap]":"Blends singing and rapping",
    "[Trap Flow]":"Modern hip-hop rhythmic cadence",
    "[Double Time]":"Twice the normal syllable rate",
    "[Spoken]":"Natural speech without singing",
    "[female lead]":"Primary female vocalist",
    "[male lead]":"Primary male vocalist",
    "[female narrator]":"Female spoken-word narration",
    "[male narrator]":"Male spoken-word narration",
    "[rap verse]":"Hip-hop verse section delivery",
    "[gospel choir]":"Inspirational multi-voice choir",
    "[diva solo]":"Showstopping single-voice performance",
    "[primal scream]":"Raw, cathartic emotional release",
    "[intimate MC]":"Close-mic, personal rap delivery",
    "Soprano":"Highest female voice range (C4 to C6)",
    "Mezzo-Soprano":"Middle female voice range (A3 to A5)",
    "Alto":"Lowest female or highest male voice range",
    "Tenor":"High male voice range (C3 to C5)",
    "Baritone":"Middle male voice range (G2 to G4)",
    "Bass":"Lowest male voice range (E2 to E4)",
    "Unspecified":"No specific voice type constraint",
    "raspy":"Gritty texture from vocal friction",
    "breathy":"Air mixed into tone for intimacy",
    "smooth":"Effortless, polished delivery",
    "silky":"Extremely smooth, refined texture",
    "warm":"Rich low-mid resonance",
    "bright":"Forward, present, high-frequency sparkle",
    "dark":"Deeper, shadowed resonance",
    "nasal":"Forward resonance through nasal cavity",
    "velvety":"Smooth with plush, deep texture",
    "powerful":"Full-voiced projection with strength",
    "delicate":"Soft, fragile, careful tone",
    "rich":"Full-bodied, complex resonance",
    "gritty":"Rough, textured vocal grain",
    "airy":"Light, open, floating quality",
    "husky":"Low and slightly rough texture",
    "piercing":"High, cutting, penetrating tone",
    "sultry":"Seductive, low, smoky quality",
    "mellow":"Soft, relaxed, gentle tone",
    "chest voice":"Strong, full lower register",
    "mixed voice":"Blend of chest and head resonance",
    "head voice":"Upper register with full resonance",
    "falsetto":"Airy upper range above normal speaking voice",
    "full range":"All registers used freely and flexibly",
    "straight-tone":"Pure tone without vibrato",
    "vibrato":"Oscillating pitch for warmth and color",
    "belting":"High-volume chest-voice push",
    "crooning":"Soft, intimate, close-mic style",
    "melisma":"Multiple notes sung per syllable",
    "runs & riffs":"Rapid melodic embellishments",
    "whisper":"Breathy, barely-voiced delivery",
    "yodel":"Rapid chest-to-falsetto switching",
    "soulful runs":"R&B-style melodic improvisation",
    "ad-libs":"Spontaneous background embellishments",
    "falsetto breaks":"Sudden jumps into upper register",
    "vocal fry":"Low, creaky, compressed tone",
    "smoky rasp":"Dark, slightly gritty texture",
    "close mic":"Intimate, breathy proximity presence",
    "warm storytelling":"Inviting, narrative warmth",
    "confident delivery":"Assured, assertive projection",
    "ethereal":"Otherworldly, floating quality",
    "resonant":"Full, projecting, ringing tone",
    "weathered":"Lived-in, aged, authentic texture",
    "restrained":"Controlled, understated expression",
  },
  fr: {
    "Aggressive":"Energie intense et confrontationnelle",
    "Boastful":"Fanfaronnade et assurance decomplexee",
    "Confident":"Energie assuree et sure d'elle-meme",
    "Contemplative":"Atmosphere reflexive et meditative",
    "Cozy":"Sentiment chaud, confortable, intime",
    "Dark":"Tonalite emotionnelle sombre",
    "Defiant":"Resistance rebelle a l'autorite",
    "Dramatic":"Tension et emotion amplifiees",
    "Dreamy":"Qualite douce, flottante, onirique",
    "Driving":"Elan rythmique vers l'avant",
    "Emotional":"Resonance emotionnelle profonde",
    "Energetic":"Energie physique et musicale elevee",
    "Epic":"Grande echelle avec envergure cinematique",
    "Ethereal":"Texture aerienne, delicate, autre-mondaine",
    "Euphoric":"Bonheur intense, elation maximale",
    "Festive":"Atmosphere festive et de celebration",
    "Groovy":"Feeling funky, rythmiquement irresistible",
    "Hype":"Montee en puissance et adrenaline",
    "Inspiring":"Energie motivante et stimulante",
    "Intimate":"Sentiment proche, personnel, vulnerable",
    "Introspective":"Reflexif, tourne vers l'interieur",
    "Joyful":"Bonheur pur et legerete",
    "Melancholic":"Tristesse douce melee de beaute",
    "Minimal":"Epure, sobre, spacieux",
    "Nostalgic":"Evoque des souvenirs chaleureux du passe",
    "Party":"Haute energie pour danser et celebrer",
    "Peaceful":"Tranquillite calme et harmonieuse",
    "Playful":"Amusement et fantaisie legere",
    "Raw":"Non poli, authentique, honnete",
    "Rebellious":"Anti-establishment, attitude punk",
    "Romantic":"Amour, desir, emotion tendre",
    "Sensual":"Seduisant, evocateur physiquement",
    "Serene":"Calme paisible et non perturbe",
    "Smooth":"Fluidite sans friction",
    "Sophisticated":"Raffine, cultive, elegant",
    "Soulful":"Authenticite emotionnelle profonde",
    "Tense":"Atmosphere anxieuse et en suspens",
    "Triumphant":"Victoire, accomplissement, depassement",
    "Uplifting":"Eleve l'esprit, energie positive",
    "Anthemic":"Qualite entrainante et collective",
    "Atmospheric":"Texture ambiante immersive",
    "Bittersweet":"Joie et tristesse entrelacees",
    "Bold":"Declaration forte et sans peur",
    "Brooding":"Obscurite profonde et lente",
    "Bubbly":"Legerete effervescente et joyeuse",
    "Calm":"Etat tranquille et sans tension",
    "Celebratory":"Marquer un achievement ou une joie",
    "Cheerful":"Lumineux, heureux, positif",
    "Cold":"Ton emotionnel detache et glacial",
    "Confessional":"Personnel, revelateur, honnete",
    "Cool":"Style decontracte et sans effort",
    "Danceable":"Entrain rythmique irresistible",
    "Deep":"Profondeur emotionnelle ou sonore dense",
    "Desolate":"Sentiment solitaire, aride et vide",
    "Dominant":"Presence autoritaire et puissante",
    "Earnest":"Sincere, authentique, non ironique",
    "Elegant":"Beaute de bon gout et raffinee",
    "Fierce":"Puissant, intense, implacable",
    "Floating":"Qualite sans gravite et suspendue",
    "Funky":"Groove syncopé et dense",
    "Futuristic":"Tourné vers l'avenir, esthetique sci-fi",
    "Gritty":"Texture rugueuse et terrestre",
    "Happy":"Emotion positive directe",
    "Haunting":"Reste en memoire, beaute etrange",
    "Heavy":"Masse sonore dense et pesante",
    "Hopeful":"Regard optimiste vers l'avenir",
    "Hypnotic":"Motif repetitif induisant la transe",
    "Laid-back":"Groove detendu et sans hate",
    "Lush":"Texture dense, riche et ample",
    "Majestic":"Grand, imposant, solennel",
    "Mystical":"Atmosphere spirituelle et mysterieuse",
    "Ominous":"Presage sombre et menaçant",
    "Passionate":"Sentiment intense et engagement fort",
    "Punchy":"Attaque forte, dynamique serree",
    "Sad":"Expression directe de la tristesse",
    "Upbeat":"Tempo rapide avec energie positive",
    "Urgent":"Sentiment pressant et immediat",
    "Vibrant":"Plein de vie et de couleur",
    "[Whispered]":"Livraison a peine audible, ton intime",
    "[Soft]":"Dynamiques douces et faible volume",
    "[Gentle]":"Livraison tendre et non agressive",
    "[Powerful]":"Projection pleine voix, haute energie",
    "[Belted]":"Voix de poitrine poussee a fort volume",
    "[Shouted]":"Fort, declaratoire, avec force",
    "[Screamed]":"Liberation emotionnelle brute, volume extreme",
    "[Intense]":"Charge emotionnelle et focus eleves",
    "[Smooth]":"Ton poli, fluide et sans effort",
    "[Raspy]":"Texture granuleuse due aux frottements vocaux",
    "[Breathy]":"Air mele au ton pour l'intimite",
    "[Airy]":"Leger, flottant, resonance ouverte",
    "[Nasal]":"Resonance nasale en avant",
    "[Soulful]":"Emotion profonde, chaleur R&B",
    "[Operatic]":"Technique de chant classique et puissance",
    "[Falsetto]":"Registre superieur au-dessus du range normal",
    "[Head Voice]":"Registre superieur avec resonance pleine",
    "[Chest Voice]":"Registre inferieur fort avec corps sonore",
    "[Melodic]":"Accent sur la melodie et la musicalite",
    "[Tender]":"Vulnerable, affectueux, doux",
    "[Aggressive]":"Approche vocale dure et attaquante",
    "[Harmonies]":"Plusieurs parties vocales superposees",
    "[Ad-libs]":"Ornements spontanes entre les lignes",
    "[Vocal Run]":"Sequence rapide de changements de hauteur",
    "[Melisma]":"Plusieurs notes sur une seule syllabe",
    "[Vibrato]":"Oscillation de hauteur pour chaleur et couleur",
    "[Staccato]":"Notes courtes, detachees et separees",
    "[Legato]":"Phrases coulantes et liees",
    "[Choir]":"Texture vocale de groupe",
    "[Chant]":"Livraison rythmique a phrase repetee",
    "[Growling]":"Distorsion vocale gutturale et agressive",
    "[Rapped]":"Livraison parlee et rythmique",
    "[Fast Rap]":"Flow rime a haute vitesse",
    "[Slow Flow]":"Rythme rap mesure et delibere",
    "[Melodic Rap]":"Melange chant et rap",
    "[Trap Flow]":"Cadence rythmique hip-hop moderne",
    "[Double Time]":"Deux fois le rythme syllabique normal",
    "[Spoken]":"Discours naturel sans chant",
    "[female lead]":"Vocaliste feminine principale",
    "[male lead]":"Vocaliste masculin principal",
    "[female narrator]":"Narration parlee feminine",
    "[male narrator]":"Narration parlee masculine",
    "[rap verse]":"Livraison de couplet hip-hop",
    "[gospel choir]":"Chorale inspirante multi-voix",
    "[diva solo]":"Performance solo epoustouflante",
    "[primal scream]":"Liberation emotionnelle crue et cathartique",
    "[intimate MC]":"Rap proche micro, personnel",
    "Soprano":"Voix feminine la plus haute (Do4 a Do6)",
    "Mezzo-Soprano":"Voix feminine mediane (La3 a La5)",
    "Alto":"Voix feminine grave ou masculine aigue",
    "Tenor":"Voix masculine aigue (Do3 a Do5)",
    "Baritone":"Voix masculine mediane (Sol2 a Sol4)",
    "Bass":"Voix masculine la plus grave (Mi2 a Mi4)",
    "Unspecified":"Aucune contrainte de type vocal",
    "raspy":"Texture granuleuse due aux frottements vocaux",
    "breathy":"Air mele au ton pour l'intimite",
    "smooth":"Livraison polie et sans effort",
    "silky":"Texture tres lisse et raffinee",
    "warm":"Riche resonance dans les mediums graves",
    "bright":"Presence avant et haute frequence",
    "dark":"Resonance plus profonde et ombree",
    "nasal":"Resonance en avant dans la cavite nasale",
    "velvety":"Lisse avec texture profonde et pleine",
    "powerful":"Projection pleine voix avec force",
    "delicate":"Ton doux, fragile et attentionne",
    "rich":"Resonance complexe et plein corps",
    "gritty":"Grain vocal brut et texture",
    "airy":"Legerete, ouverture, qualite flottante",
    "husky":"Grave et legerement rugueux",
    "piercing":"Aigu, tranchant, penetrant",
    "sultry":"Seduisant, grave et fume",
    "mellow":"Doux, detendu, ton gentil",
    "chest voice":"Registre grave fort et plein",
    "mixed voice":"Melange de resonance thoracique et de tete",
    "head voice":"Registre superieur avec ton plein",
    "falsetto":"Range superieur aerien au-dessus de la voix normale",
    "full range":"Tous les registres utilises librement",
    "straight-tone":"Ton pur sans vibrato",
    "vibrato":"Oscillation de hauteur pour chaleur et couleur",
    "belting":"Poussee de voix de poitrine a fort volume",
    "crooning":"Style doux, intime, proche micro",
    "melisma":"Plusieurs notes par syllabe",
    "runs & riffs":"Ornements melodiques rapides",
    "whisper":"Livraison a peine exprimee et respiree",
    "yodel":"Alternance rapide poitrine-falsetto",
    "soulful runs":"Improvisation melodique style R&B",
    "ad-libs":"Ornements spontanes en arriere-plan",
    "falsetto breaks":"Sauts soudains vers le registre superieur",
    "vocal fry":"Ton grave, craquant et compresse",
    "smoky rasp":"Texture sombre et legerement granuleuse",
    "close mic":"Proximite intime et presence respiree",
    "warm storytelling":"Chaleur narrative et accueillante",
    "confident delivery":"Projection assuree et assertive",
    "ethereal":"Qualite autre-mondaine et flottante",
    "resonant":"Son plein, projectif et vibrant",
    "weathered":"Texture vecue, vieillie et authentique",
    "restrained":"Expression controlee et sobre",
  }
};
